### ISSUE TITLE
Useful links

### ISSUE THREAD

**Issue by fdiblen** [tortellini-tools/action#1]
https://choosealicense.com/
https://the-turing-way.netlify.app/reproducible-research/licensing/licensing-software.html
https://the-turing-way.netlify.app/reproducible-research/licensing/licensing-compatibility.html

**Comment by sverhoeven** [comment]
https://the-turing-way.netlify.app/reproducible-research/licensing/licensing-software.html

**Comment by jspaaks** [comment]
- https://reuse.software/comparison/
- https://pypi.org/project/reuse/
- https://git.gfz-potsdam.de/id2/software/services/fair/software-quality-assurance

(from suggestions from @mdolling-gfz over at research-software-directory: https://github.com/research-software-directory/research-software-directory/issues/766)

**Comment by sverhoeven** [comment]
https://github.com/librariesio/license-compatibility - Check compatibility between different SPDX licenses, used by Libraries.io for checking dependency license compatibility.

**Comment by sverhoeven** [comment]
https://spdx.dev/ 
  - has yaml schema spec for listing software with their dependencies and licenses
  - has list of tools

**Comment by sverhoeven** [comment]
Primary programming language on RSD:
```
curl https://research-software.nl/api/software > software.json
jq '.[].programmingLanguage[0]' < software.json  |sort |uniq -c |sort -rn
     98 "Python"
     24 "Java"
     16 "JavaScript"
      8 "C++"
      5 "MATLAB"
      4 "YAML"
      4 "TypeScript"
      4 "R"
      3 "SPARQL"
      3 "C"
      2 "Fortran"
      1 "Shell scripts"
      1 "PHP"
      1 null
      1 "Haskell"
      1 "Go"

```

**Comment by sverhoeven** [comment]
[Docs on GitLab CI job for License Compliance](https://docs.gitlab.com/ee/user/compliance/license_compliance/) - uses https://github.com/pivotal/LicenseFinder

**Comment by sverhoeven** [comment]
Can we convert this to a awesome list or store it elsewhere?

**Comment by sverhoeven** [comment]
https://github.com/philips-software/spdx-action - action which calls ort and then creates a spdx file

**Comment by sverhoeven** [comment]
Can we close this? It served its purpose.
