### ISSUE TITLE
verify that example workflows use versioned action

### ISSUE THREAD

**Issue by jspaaks** [tortellini-tools/action#101]
once there is a stable release

e.g. here

https://github.com/tortellini-tools/action/blob/3e49645ef641960997ea8c4908ab0fcc72c561b8/.github/workflows/tortellini.yml#L23-L25

**Comment by sverhoeven** [comment]
The examples in the README.md should use version (`v3`) instead of `main`.

How the example workflows should be updated should be added to the [How to create a release chapter](https://github.com/tortellini-tools/action/blob/main/README.dev.md#how-to-create-a-release) .

**Comment by fdiblen** [comment]
Implemented in #141 and waiting for a new release.

**Comment by sverhoeven** [comment]
Fixed in PR #141
