### ISSUE TITLE
Clean up after ourselves

### ISSUE THREAD

**Issue by sverhoeven** [tortellini-tools/action#102]
Remove `in/` folder and clean up intermediate files in `out/` folder once the ort commands have been run

**Comment by fdiblen** [comment]
Typescript code should do the clean up.

**Comment by sverhoeven** [comment]
During https://github.com/NLeSC/tortellini-on-rsd/actions/runs/896534020 run a warning 
`You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 46 MB` got generated.

**Comment by jspaaks** [comment]
My suggestion on how to do this is to do it like @sverhoeven did it in his bash script https://github.com/tortellini-tools/action/blob/475e573aa7be486ad97daa8a3ed7a2136daf3801/ort/run.sh#L27

That way, we don;t have to deal with permissions

**Comment by sverhoeven** [comment]
We should keep, per repo, the html and gitlab json file as they are needed as output and tests

**Comment by fdiblen** [comment]
done in #119
