### ISSUE TITLE
can we be consistent with clone folder path?

### ISSUE THREAD

**Issue by fdiblen** [tortellini-tools/action#113]
`check_directory()` and `check_urls() are doing very similar things. I expect `check_directory()` to have a similar path for `input_dir` as in `check_urls()`.

**Comment by sverhoeven** [comment]
Indeed they do similar things. In https://github.com/tortellini-tools/action/issues/86 I showed that inside `check_urls` we could call `check_directory` on each cloned repo.

The idea is that `check_directory` defaults to `.` as that is the default behavior when we want to run on currently checked out repo.
However when `check_directory` is called within `check_urls` you pass the directory where you cloned the repo.
