### ISSUE TITLE
Add to Research Software Directory

### ISSUE THREAD

**Issue by sverhoeven** [tortellini-tools/action#138]
It would be nice to see this action shown on https://www.research-software.nl/. Can it be added?

Fixing #137 first will help gather texts for the RSD entry.

**Comment by jspaaks** [comment]
done as much as is possible now https://www.research-software.nl/software/tortellini-github-action

could still use a conceptdoi for showing the citation information, but that only happens after v3 is released

**Comment by sverhoeven** [comment]
RSD page looks good
