### ISSUE TITLE
WIP-scancode-toolkit

### ISSUE THREAD

**Issue by fdiblen** [tortellini-tools/action#15]
**Describe which command line tool or service you are going to evaluate.**
For each repository you are using to evaluate create a new comment in this issue.

https://github.com/nexB/scancode-toolkit

**Describe commands / output used to evaluate**

Create a virtual environment
```
python3 -m venv env
. ./env/bin/activate
pip install --upgrade pip setuptools wheel
```
Install scancode-toolkit (55 MB)
```
pip install scancode-toolkit[full] 
```

**Describe pros and cons of the tool**

**Questions that need answers:**
1. Can tool/service be given multiple repository URLs to check?
1. Can tool/service be given a repostory URL to check, if not describe how to check repository?
1. What kind of feedback does tool return about compliance, if so please show example?

**Questions that would be nice to answers:**
1. Which software package registries was used during evaluation? For example pure python uses pypi or R uses cran + bioconductor or did it find sub directories with package.json
1. Which dependency resolver / build chain was use during evaluation? For example requirement.txt with pip or environment.yml with conda
1. Can tool handle dependency with multiple licenses?
1. Does it check between runtime and other sets of dependencies? Can it be forced to check runtime only?

**Other features:**
Support Linux/Win/Mac

**Comment by jspaaks** [comment]
As far as I can tell, scancode is limited to scanning existing files, it does not attempt to resolve dependencies or interpret dependency files.

![image](https://user-images.githubusercontent.com/4558105/117655554-81281d80-b197-11eb-8b3a-44acd66aec97.png)
from https://scancode-toolkit.readthedocs.io/en/latest/explanations/overview.html#how-does-scancode-work

For example when I do
```shell
cd $(mktemp -d --tmpdir scancode.XXXXXX)
git clone https://github.com/sequgen/sequgen .
scancode --json report.json -clpeui .
```

It does not find anything related to `matplotlib` or `numpy` which are listed in `setup.py`. 

I think this disqualifies ScanCode for our purposes
