### ISSUE TITLE
list of external tools

### ISSUE THREAD

**Issue by fdiblen** [tortellini-tools/action#2]
1. https://github.com/pivotal/LicenseFinder #4
1. https://gist.github.com/bouweandela/13ab56bee8778a1eb5b82091e4fdd443 #19
1. https://github.com/abduhbm/dep-license #6 #16
1. https://pypi.org/project/license-sh/ #23 #7
1. https://github.com/delfrrr/npm-consider #21
1. https://github.com/davglass/license-checker #24 
1. https://github.com/wimglenn/johnnydep/ can output deps with a license each
1.

**Comment by sverhoeven** [comment]
https://github.com/nexB/scancode-toolkit - multi lang? #15
https://github.com/oss-review-toolkit/ort - multi lang #13

https://github.com/github/licensed - written in Ruby, multi lang 
https://github.com/Softwarepark/licenseguard - wrapper around license-checker

**Comment by fdiblen** [comment]
https://github.com/librariesio/license-compatibility #14

**Comment by sverhoeven** [comment]
From https://github.com/oss-review-toolkit/ort/blob/master/docs/design.md
- https://github.com/blackducksoftware/synopsys-detect
- https://github.com/librariesio/bibliothecary - Libraries.io Package Manager Manifest Parsers
- https://github.com/snyk/snyk - [license compliance costs money](https://support.snyk.io/hc/en-us/articles/360015235618-Getting-Started-with-Snyk-License-Compliance-Management)

**Comment by sverhoeven** [comment]
Decided to go with ort
