### ISSUE TITLE
Name for the tool

### ISSUE THREAD

**Issue by sverhoeven** [tortellini-tools/action#26]
licenseguard is already taken.

Let come up with something better.

The name should be free on 
- GitHub organization
- Npmjs
- GitHub marketplace

**Comment by sverhoeven** [comment]
- batchort

**Comment by jspaaks** [comment]
- **pulledover** As in, "_license and registration please_"
- **ortolan** (a bird, but also an infamous recipe that people may object to)

**Comment by jspaaks** [comment]
My suggestion:

- repo: `ortolan-tools/ortolan` (npm package)
    - `ortolan` can take a local dir, one url:string, or urls:string[] as input
    - comes packaged with its own NLeSC specific default config files
    - runs dockerized `ort`
    - optionally calculates summary statistics

- repo: `ortolan-tools/action` (action)
    - name in the `action.yml`: "ortolan"
    - runs `ortolan`

- repo:`NLeSC/ortolan-batch-rsd` (workflow)
    - on:scheduled
        - creates list of repos from RSD API
        - runs `ortolan-tools/action` action `with` list of repos
        - uploads the results to S3

**Comment by jspaaks** [comment]
github orgs:

   - ~~fortress~~ taken by user
   - ~~ort~~ taken, and nicer not to namesquat
   - ~~orthicon~~ taken, no public activity
   - ~~ortolan-tools~~
   - ~~ortolan~~ taken, no public activity
   - ~~pulledover~~ taken, no public activity
   - ~~tortellini~~ taken, no public activity
   - orthicon-tools
   - porterhouse-tools
   - tortellini-tools

npmjs package names:

   - ~~bort~~
   - ~~fortress~~
   - ~~ortolan~~
   - ~~pulledover~~
   - ~~tortellini~~
   - batchort
   - orthicon
   - porterhouse

marketplace names:

   - ~~bort~~
   - ~~ort~~ free, but nicer not to namesquat
   - ~~ortolan~~
   - ~~pulledover~~
   - batchort
   - fortress
   - orthicon (oldskool television tube)
   - porterhouse (a type of steak)
   - tortellini


My current preference: `github.com/porterhouse-tools/porterhouse` or `github.com/orthicon-tools/orthicon`

**Comment by sverhoeven** [comment]
* ortts,  ort typescript / plural ort with typo
  * Not in use on GitHub org, npmjs and marketplace

**Comment by sverhoeven** [comment]
Decided on tortellini repo and tortellini-tools for organization

**Comment by sverhoeven** [comment]
Next up is to replace `licenseguard` to  `tortellini`

**Comment by jspaaks** [comment]
Also, replace ortolan and batchort with tortellini

**Comment by sverhoeven** [comment]
Due to GH marketplace restrictions, we had to use `tortellini-tools/action`

**Comment by sverhoeven** [comment]
Fixed in #83
