### ISSUE TITLE
Arrange AWS S3 bucket

### ISSUE THREAD

**Issue by sverhoeven** [tortellini-tools/action#28]
And store details in LastPass

Should have enough space to store all reports, around 2Gb.

The bucket should have a nice URL that is public, 
URL could be: tortellini.research-software.nl

**Comment by jspaaks** [comment]
https://tortellini-bkt2-5uk3-fbnr.s3.eu-central-1.amazonaws.com/tortellini-results/hello-s3.txt

details in LastPass

**update** file was removed during #80

**Comment by jspaaks** [comment]
https://tortellini-bkt2-5uk3-fbnr.s3.eu-central-1.amazonaws.com/out/FAIR-data-for-CAPACITY/FHIR-to-CAPACITY/scan-report-web-app.html

**Comment by sverhoeven** [comment]
I created a CNAME record for tortellini.research-software.nl to tortellini-bkt2-5uk3-fbnr.s3.eu-central-1.amazonaws.com .

However visiting https://tortellini.research-software.nl/out/FAIR-data-for-CAPACITY/FHIR-to-CAPACITY/scan-report-web-app.html gives not found error with 
```
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<BucketName>tortellini.research-software.nl</BucketName>
<RequestId>MP8XAKMSRV6DYAZF</RequestId>
<HostId>pZ2X/sORWi/tfLiLTmJQhnJX9Pj3zYuL7LI48fhrfeQrEOsvQ/0wNJs5lxVGM4O6x70jsHepSTk=</HostId>
</Error>
```

According to https://www.scaleway.com/en/docs/s3-customize-bucket-domain/ the bucket should be named `tortellini.research-software.nl`.

**Comment by jspaaks** [comment]
Made a second bucket, ran the workflow from tortellini-on-rsd (https://github.com/NLeSC/tortellini-on-rsd/runs/2774756029?check_suite_focus=true), looks like it is working http://tortellini.research-software.nl/index.html

**Comment by fdiblen** [comment]
done in https://github.com/NLeSC/tortellini-on-rsd/pull/5
