### ISSUE TITLE
Integration test on external repo

### ISSUE THREAD

**Issue by sverhoeven** [tortellini-tools/action#33]
Workflow should test https://github.com/fair-software/howfairis with ort.

The format `GitLabLicenseModel` which generates `gl-license-scanning-report.json` file should be compared with manual ort run.

Other files have timestamps and sha-key and are harder to compare.

**Comment by sverhoeven** [comment]
This issue is about running the action on a single external repo. 

However in https://github.com/tortellini-tools/action/blob/main/.github/workflows/usage.yml and https://github.com/tortellini-tools/action/blob/5fbc2c7fccbd5f416617c393e4572912ad935bb4/.github/workflows/testing.yml#L172-L202 workflows the howfairis repo is tested as member of a list of repos.

In #32 the test workflow jobs will be extended to compare content of json files against manual ort run.

Do we still need need this test?

**Comment by jspaaks** [comment]
Here's how I understand the different purposes:

- **usage.yml** is to show others how this action may be used
- **testing** is for tortellini developers to see what breaks while doing development
- #32 is to verify that the result is what it should be, specifically, to verify that the tortellini wrapper around ort is not messing up the results somehow.
