### ISSUE TITLE
Add function to run ort on a single repo

### ISSUE THREAD

**Issue by sverhoeven** [tortellini-tools/action#34]
Similar to https://github.com/NLeSC/licenseguard/blob/rsd-software-vs-ort/ort/run.sh but then in Typescript.

Only generate reports for
- scan-report-web-app.html, WebApp format in `ort report`
- out.txt, captured stdout/stderr of Docker containers.
- evaluation-result.yml, output from `ort evaluate`

**Comment by jspaaks** [comment]
How do we plan on calling docker from TypeScript? [shelljs](https://www.npmjs.com/package/shelljs)?

`shell.exec("docker run --rm -v etc")`

**Comment by sverhoeven** [comment]
I would suggest to use https://github.com/actions/toolkit/tree/main/packages/exec as its already part of the GH action ecosystem.

**Comment by sverhoeven** [comment]
Split up into #74, #76 and #78
