### ISSUE TITLE
Create index.html Vue App

### ISSUE THREAD

**Issue by sverhoeven** [tortellini-tools/action#36]
Vue app index.html which shows index-latest.json in a table.

Similar to https://github.com/fair-software/fairtally/blob/main/fairtally/data/index.html.template, instead of [inlining data](https://github.com/fair-software/fairtally/blob/bb5f47dd49c74f031729ac181628f2ae35bdb3fe/fairtally/data/index.html.template#L164) fetch json file.

**Comment by jspaaks** [comment]
working off of the data structure in https://github.com/tortellini-tools/action/issues/35#issuecomment-856541067 for the moment, but easy enough to change

**Comment by jspaaks** [comment]
PR #122

**Comment by fdiblen** [comment]
done in #122.
