### ISSUE TITLE
Example workflow for multiple urls in README

### ISSUE THREAD

**Issue by sverhoeven** [tortellini-tools/action#37]
Provide example workflow which uses 2 repositories in README to show what it does.

For now we don't need to have the output files, we just want to know the ort analyse ran OK.

**Comment by fdiblen** [comment]
Can we close this?

**Comment by jspaaks** [comment]
autoclosed, reopen

**Comment by sverhoeven** [comment]
The [.github/workflows/tortellini.yml](https://github.com/tortellini-tools/action/blob/main/.github/workflows/tortellini.yml) runs the example workflow. It was run at https://github.com/tortellini-tools/action/runs/2712497139?check_suite_focus=true

I expected to see `out/*/*/analyzer-result.yml` files with the tree command however the output dirs are empty. Also as the cloned repo is not cleaned up in the code I expected to see cloned repos in `in/*/*/` directories.

**Comment by sverhoeven** [comment]
Nevermind it is the `tree -L 3` that does not show the files. Can the level be increased to 4?

**Comment by sverhoeven** [comment]
Output of workflow has been made more verbose so issue can be closed.

**Comment by sverhoeven** [comment]
Done in #95
