### ISSUE TITLE
RSD GH workflow

### ISSUE THREAD

**Issue by sverhoeven** [tortellini-tools/action#38]
Create repo `NLeSC/tortellini-rsd` in NLeSC organization with a workflow that  runs our action on repositories of software items of RSD.

The workflow should use [on:workflow_dispatch](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch) so it can be triggered manually.

**Comment by jspaaks** [comment]
I created https://github.com/NLeSC/tortellini-rsd with a workflow file tha tcan be triggered by hand. It collects github repository URLS from the Research Software Directory, puts them in a file `urls.txt`, which is then passed as an input argument to the action (which doesn't understand the `repositories` input argument at the moment, but @fdiblen is working on that in PR #94)

**Comment by fdiblen** [comment]
can we close this?
