### ISSUE TITLE
consolidate the information in requirements.txt, PLAN.md

### ISSUE THREAD

**Issue by jspaaks** [tortellini-tools/action#49]
Currently there is some duplication, some conflicting information, and some outdated information in requirements.txt and PLAN.md. 

I'd like us to consolidate that information such that it is DRY and accurate. Probably this means that we'll end up with one file, README.md

**Comment by sverhoeven** [comment]
Define goal of software

**Comment by sverhoeven** [comment]
Done in PR #112
