### ISSUE TITLE
Can we just use dependency files combined with a resolver?

### ISSUE THREAD

**Issue by jspaaks** [tortellini-tools/action#5]
(For PyPI)

Maybe something like https://github.com/pypa/pip/blob/e6414d6db6db37951988f6f2b11ec530ed0b191d/src/pip/_vendor/resolvelib/resolvers.py#L472-L474

Feed requirements from setup.cfg or setup.py to resolver,

Then you could get the license via
```
curl -s -H 'Accept: application/json' https://pypi.org/pypi/howfairis/json | jq ."info"."license"
"Apache Software License 2.0"
```
Interestingly, PyPI assigns a given license to all versions of the tool (as does github BTW) so maybe there's no point to resolving a version, just the package name is enough

**Comment by sverhoeven** [comment]
Ort performs install so longer applicable?
