### ISSUE TITLE
Make citable

### ISSUE THREAD

**Issue by sverhoeven** [tortellini-tools/action#50]
Follow the fair software recommendations by adding:
* CITATION.cff, 
* .zenodo.json, 
* workflow to check citation file format,
* Enable Zenodo integration so a GH release will produce a DOI.
* Update [CODEOWNERS file](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) to have GH usernames of owners.

**Comment by jspaaks** [comment]
PR #115. Also enabled zenodo integration on this github org and toggled the switch on zenodo.org. 

Not sure I like CODEOWNERS

**Comment by jspaaks** [comment]
PR was merged, can we close this?

**Comment by fdiblen** [comment]
created an issue to remove CODEOWNERS #121. The rest is implemented.
