### ISSUE TITLE
Example usage

### ISSUE THREAD

**Issue by sverhoeven** [tortellini-tools/action#58]
Most GH actions have a ready to copy paste example in their README. We should also have an example.

According to https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#creating-a-readme the README should have:
* A detailed description of what the action does.
* Required input and output arguments.
* Optional input and output arguments.
* Secrets the action uses.
* Environment variables the action uses.
* **An example of how to use your action in a workflow.**

**Comment by sverhoeven** [comment]
Once #71 PR is merged there already is test-action job in .github/workflows/testing.yml which does this, but it uses . instead of tortellini-tools/action@v1 which makes it only work on this repo and not some random repo.

**Comment by sverhoeven** [comment]
We should add a workflow to test the main branch using `tortellini-tools/action@main`

**Comment by fdiblen** [comment]
Fixed in #92
