### ISSUE TITLE
Run ort evaluate

### ISSUE THREAD

**Issue by sverhoeven** [tortellini-tools/action#76]
Currently only the `ort analysis` giving a list of dependencies with their licenses. To get insight how compliant the licenses are we need to run `ort evaluate`. The evaluate command will need to mount in the default ort config files from the `conf/` directory.

In a GH workflow the action should produce a `evaluation-result.yml` file for each repo.

**Comment by jspaaks** [comment]
`evaluate` needs a couple of config files, which are currently in `/conf`. We should consider bundling these files with the distributable package you get from `npm run package`.

possibly need to uses `files` in the `package.json`, see https://docs.npmjs.com/cli/v7/configuring-npm/package-json#files

**Comment by jspaaks** [comment]
I think we should consider requiring that the rules file and the classification file reside in the repository that has the workflow (as opposed to as part of the tool)

ort evaluate needs to be passed a

1. curations file
2. rules file
3. license classification file

The curations file should be an optional file that is read from the repository itself, so you dont have to curl it, you already have it when you do a `checkout` in the workflow, or a `clone` in the typescript. I suggest that by default we have the action look for a file called `.tortellini.yml` in the root of the repo.

I think 2 and 3 should come from whoever/whatever triggers the workflow, my suggestion would be to just do a curl in the workflow, like we did here https://github.com/tortellini-tools/action/blob/475e573aa7be486ad97daa8a3ed7a2136daf3801/ort/prep.sh#L8-L9. We can host nlesc-specific rules in nlesc/tortellini-on-rsd.

The action should then accept 2 new arguments, `rules` and `classifications`, both of type string, each containing the relative path to the file. These arguments' values are then used when making the call to `docker run ... ort evaluate ... `

**Comment by jspaaks** [comment]
PR was merged, can we close this?
