### ISSUE TITLE
Run ort report

### ISSUE THREAD

**Issue by sverhoeven** [tortellini-tools/action#78]
To get a human readable report from the `ort evaluate` yaml file we need to run `ort report -f WebApp`.

The action should generate a `scan-report-web-app.html` file for each repository url.

**Comment by jspaaks** [comment]
PR was merged, can we close this?

**Comment by fdiblen** [comment]
At the moment the action only generates a yaml file but not a web app.

**Comment by fdiblen** [comment]
Can we close this?

**Comment by fdiblen** [comment]
implemented in #118.
