### ISSUE TITLE
Example workflow to show the report 

### ISSUE THREAD

**Issue by sverhoeven** [tortellini-tools/action#79]
Workflow can [upload artifact action](https://github.com/marketplace/actions/upload-a-build-artifact) to make tarball with generated files available.

**Comment by jspaaks** [comment]
PR was merged, can we close this?

**Comment by fdiblen** [comment]
We still need to show this in example workflow (usage.yml) and in README.md.

**Comment by sverhoeven** [comment]
Done in PR #136
