### ISSUE TITLE
Upload results to S3 in RSD workflow

### ISSUE THREAD

**Issue by sverhoeven** [tortellini-tools/action#80]
The RSD workflow should make its generated files available to browse online. 
The workflow should be extended with a step to upload the files to an S3 bucket.
Uploading could be done with https://github.com/jakejarvis/s3-sync-action action.

Blocked by #28

**Comment by jspaaks** [comment]
https://github.com/NLeSC/tortellini-on-rsd/pull/5 resulted in https://tortellini-bkt2-5uk3-fbnr.s3.eu-central-1.amazonaws.com/out/FAIR-data-for-CAPACITY/FHIR-to-CAPACITY/scan-report-web-app.html

**Comment by jspaaks** [comment]
~~Link now includes `.tortellini`: https://tortellini-bkt2-5uk3-fbnr.s3.eu-central-1.amazonaws.com/.tortellini/out/FAIR-data-for-CAPACITY/FHIR-to-CAPACITY/scan-report-web-app.html~~

**Comment by jspaaks** [comment]
https://tortellini.research-software.nl/index.html from https://github.com/NLeSC/tortellini-on-rsd/runs/2774756029?check_suite_focus=true

**Comment by fdiblen** [comment]
done in https://github.com/NLeSC/tortellini-on-rsd/pull/5
