### ISSUE TITLE
Add input arguments to use custom ort config files

### ISSUE THREAD

**Issue by sverhoeven** [tortellini-tools/action#81]
By default the ort config files in https://github.com/NLeSC/tortellini-on-rsd/tree/main/config will be used. To make the more customizable to company policies it would be nice to be able to supply my own config files.

The following input parameters of the action should added
- curations: config/curations.yml or https://github.com/NLeSC/tortellini-on-rsd/blob/main/config/curations.yml
- rules: config/rules.kts or https://github.com/NLeSC/tortellini-on-rsd/blob/main/config/rules.kts
- classifications: config/license-classifications.yml or https://github.com/NLeSC/tortellini-on-rsd/blob/main/config/license-classifications.yml

Where `config/` is a directory is relative to the current working directory of the workflow step in which our action is called.
The `config/*` could part of the repo that is being analysed or generated somehow in a previous step.

**Comment by jspaaks** [comment]
Can we close this?
